### ISSUE TITLE
error with androserver

### ISSUE THREAD

**Issue by Axe-Usa** [wszf/androrat#12]
hello i get these errors in server when i want to load the apk
```
01-01 00:03:31.570: E/Trace(1505): error opening trace file: No such file or directory (2)
01-01 00:03:31.620: W/asset(1505): Asset path /data/app/my.app.client-1.apk is neither a directory nor file (type=1).
01-01 00:03:31.750: W/asset(1505): Asset path /data/app/my.app.client-1.apk is neither a directory nor file (type=1).
01-01 00:03:31.770: D/AndroidRuntime(1505): Shutting down VM
01-01 00:03:31.790: W/dalvikvm(1505): threadid=1: thread exiting with uncaught exception (group=0x417b2930)
01-01 00:03:32.340: E/AndroidRuntime(1505): FATAL EXCEPTION: main
01-01 00:03:32.340: E/AndroidRuntime(1505): java.lang.RuntimeException: Unable to instantiate receiver my.app.client.BootReceiver: java.lang.ClassNotFoundException: Didn't find class "my.app.client.BootReceiver" on path: /data/app/my.app.client-1.apk
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2357)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at android.os.Looper.loop(Looper.java:137)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at java.lang.reflect.Method.invoke(Method.java:511)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at dalvik.system.NativeStart.main(Native Method)
01-01 00:03:32.340: E/AndroidRuntime(1505): Caused by: java.lang.ClassNotFoundException: Didn't find class "my.app.client.BootReceiver" on path: /data/app/my.app.client-1.apk
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2352)
01-01 00:03:32.340: E/AndroidRuntime(1505): 	... 10 more
01-01 00:08:32.860: I/Process(1505): Sending signal. PID: 1505 SIG: 9

```
thx in advance!

**Comment by Axe-Usa** [comment]
I tried compile it Including the inOut files etc..
but show me a lot of errors
![capture](https://cloud.githubusercontent.com/assets/23561866/26418934/e7e7ad28-4072-11e7-8a41-749192bccb26.PNG)
