### ISSUE TITLE
Cant run Androrat

### ISSUE THREAD

**Issue by ma3axaka007** [wszf/androrat#9]
```
08-31 11:57:15.669 3878-3878/my.app.client I/System.out: 192.168.3.100
08-31 11:57:15.669 3878-3878/my.app.client I/System.out: 9999
08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 192.168.3.100
08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 9999
08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 192.168.3.100
08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 9999
08-31 11:57:15.709 3878-3878/my.app.client I/ViewRootImpl: CPU Rendering VSync enable = true
08-31 11:57:15.719 3878-3921/my.app.client D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-31 11:57:15.719 3878-3878/my.app.client D/Atlas: Validating map...
08-31 11:57:15.729 3878-3878/my.app.client D/ActivityThreadInjector: clearCachedDrawables.
08-31 11:57:15.749 3878-3878/my.app.client I/Client: In onCreate
08-31 11:57:15.759 3878-3878/my.app.client I/Client: onStartCommand by: my.app.client.LauncherActivity
08-31 11:57:15.769 3878-3878/my.app.client I/Client: Try to connect to 192.168.3.100:9999
08-31 11:57:15.769 3878-3878/my.app.client D/AndroidRuntime: Shutting down VM
08-31 11:57:15.769 3878-3878/my.app.client E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: my.app.client, PID: 3878
                                                             java.lang.RuntimeException: Unable to start service my.app.client.Client@34e18bec with Intent { act=my.app.client.LauncherActivity cmp=my.app.client/.Client (has extras) }: android.os.NetworkOnMainThreadException
                                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2932)
                                                                 at android.app.ActivityThread.access$2100(ActivityThread.java:154)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
                                                              Caused by: android.os.NetworkOnMainThreadException
                                                                 at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
                                                                 at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:110)
                                                                 at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
                                                                 at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                 at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:163)
                                                                 at java.net.Socket.startupSocket(Socket.java:590)
                                                                 at java.net.Socket.tryAllAddresses(Socket.java:128)
                                                                 at java.net.Socket.<init>(Socket.java:178)
                                                                 at java.net.Socket.<init>(Socket.java:150)
                                                                 at out.Connection.connect(Connection.java:52)
                                                                 at my.app.client.Client.onStartCommand(Client.java:96)
                                                                 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2915)
                                                                 at android.app.ActivityThread.access$2100(ActivityThread.java:154) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
08-31 11:57:15.769 3878-3878/my.app.client I/Process: Sending signal. PID: 3878 SIG: 9
```

See this message in logcat
Builded with Android Studio 2.1

**Comment by stratrik** [comment]
Please explain your build env, i may be able to help.


On Wednesday, August 31, 2016, ma3axaka007 <notifications@github.com> wrote:
> 08-31 11:57:15.669 3878-3878/my.app.client I/System.out: 192.168.3.100
> 08-31 11:57:15.669 3878-3878/my.app.client I/System.out: 9999
> 08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 192.168.3.100
> 08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 9999
> 08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 192.168.3.100
> 08-31 11:57:15.679 3878-3878/my.app.client I/System.out: 9999
> 08-31 11:57:15.709 3878-3878/my.app.client I/ViewRootImpl: CPU Rendering
VSync enable = true
> 08-31 11:57:15.719 3878-3921/my.app.client D/OpenGLRenderer: Use
EGL_SWAP_BEHAVIOR_PRESERVED: true
> 08-31 11:57:15.719 3878-3878/my.app.client D/Atlas: Validating map...
> 08-31 11:57:15.729 3878-3878/my.app.client D/ActivityThreadInjector:
clearCachedDrawables.
> 08-31 11:57:15.749 3878-3878/my.app.client I/Client: In onCreate
> 08-31 11:57:15.759 3878-3878/my.app.client I/Client: onStartCommand by:
my.app.client.LauncherActivity
> 08-31 11:57:15.769 3878-3878/my.app.client I/Client: Try to connect to
192.168.3.100:9999
> 08-31 11:57:15.769 3878-3878/my.app.client D/AndroidRuntime: Shutting
down VM
> 08-31 11:57:15.769 3878-3878/my.app.client E/AndroidRuntime: FATAL
EXCEPTION: main
> Process: my.app.client, PID: 3878
> java.lang.RuntimeException: Unable to start service
my.app.client.Client@34e18bec with Intent {
act=my.app.client.LauncherActivity cmp=my.app.client/.Client (has extras)
}: android.os.NetworkOnMainThreadException
> at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2932)
> at android.app.ActivityThread.access$2100(ActivityThread.java:154)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:135)
> at android.app.ActivityThread.main(ActivityThread.java:5290)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
> Caused by: android.os.NetworkOnMainThreadException
> at
android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
> at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:110)
> at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
> at libcore.io.IoBridge.connect(IoBridge.java:122)
> at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
> at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:163)
> at java.net.Socket.startupSocket(Socket.java:590)
> at java.net.Socket.tryAllAddresses(Socket.java:128)
> at java.net.Socket.<init>(Socket.java:178)
> at java.net.Socket.<init>(Socket.java:150)
> at out.Connection.connect(Connection.java:52)
> at my.app.client.Client.onStartCommand(Client.java:96)
> at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2915)
> at android.app.ActivityThread.access$2100(ActivityThread.java:154)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:135)
> at android.app.ActivityThread.main(ActivityThread.java:5290)
> at java.lang.reflect.Method.invoke(Native Method)
> at java.lang.reflect.Method.invoke(Method.java:372)
> at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
> 08-31 11:57:15.769 3878-3878/my.app.client I/Process: Sending signal.
PID: 3878 SIG: 9
>
> See this message in logcat
> Builded with Android Studio 2.1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
*PGP Public Key <http://goo.gl/dZVCNO>*

**Comment by matteke-games** [comment]
@stratrik it just means that a socket is opened on the main thread. If you have a fix for that then please share it

**Comment by joelmullins** [comment]
Thanks
